package web

import "embed"

// The browser-facing side of the application ships inside the binary, so a
// deployment is still one artefact and templates can never be out of step with
// the code that executes them.
//
// static/css/app.css is generated by `make assets` from the Tailwind standalone
// binary and committed, which is what keeps npm out of the toolchain
// (DESIGN.md §9.2). static/js/htmx.min.js is vendored for the same reason.

//go:embed templates
var templateFS embed.FS

//go:embed static
var staticFS embed.FS
