// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateDocumentID = `-- name: AllocateDocumentID :one
update collections
set next_serial = case when id_strategy = 'serial' then next_serial + 1 else next_serial end
where id = $1
returning id_field, id_strategy, (next_serial - 1)::bigint as allocated
`

type AllocateDocumentIDRow struct {
	IDField    string
	IDStrategy string
	Allocated  int64
}

// AllocateDocumentID reserves the next identifier for a create.
//
// The counter is advanced in the same statement that reads it, so two
// concurrent creates cannot be handed the same number: the second waits on the
// row lock the first is holding and reads the value the first left behind.
// `next_serial - 1` is returned because `returning` sees the new row, and what
// the caller wants is the value it just claimed rather than the one after it.
//
// The counter is left alone under id_strategy = 'uuid', where the caller
// generates its own identifier and `allocated` is ignored.
func (q *Queries) AllocateDocumentID(ctx context.Context, id pgtype.UUID) (AllocateDocumentIDRow, error) {
	row := q.db.QueryRow(ctx, allocateDocumentID, id)
	var i AllocateDocumentIDRow
	err := row.Scan(&i.IDField, &i.IDStrategy, &i.Allocated)
	return i, err
}

const collectionByOwnerAndID = `-- name: CollectionByOwnerAndID :one
select c.id, c.project_id, c.name, c.seed, c.id_field, c.id_strategy, c.next_serial, c.created_at, c.updated_at from collections c
join projects p on p.id = c.project_id
where c.id = $1 and p.owner_id = $2
`

type CollectionByOwnerAndIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) CollectionByOwnerAndID(ctx context.Context, arg CollectionByOwnerAndIDParams) (Collection, error) {
	row := q.db.QueryRow(ctx, collectionByOwnerAndID, arg.ID, arg.OwnerID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Seed,
		&i.IDField,
		&i.IDStrategy,
		&i.NextSerial,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const collectionByOwnerAndName = `-- name: CollectionByOwnerAndName :one
select c.id, c.project_id, c.name, c.seed, c.id_field, c.id_strategy, c.next_serial, c.created_at, c.updated_at from collections c
join projects p on p.id = c.project_id
where p.owner_id = $1 and p.slug = $2 and c.name = $3
`

type CollectionByOwnerAndNameParams struct {
	OwnerID pgtype.UUID
	Slug    string
	Name    string
}

// CollectionByOwnerAndName resolves the {slug} and {name} of the reset URL in
// one statement, so that a name in another account's project is the same 404 as
// a name that was never used.
func (q *Queries) CollectionByOwnerAndName(ctx context.Context, arg CollectionByOwnerAndNameParams) (Collection, error) {
	row := q.db.QueryRow(ctx, collectionByOwnerAndName, arg.OwnerID, arg.Slug, arg.Name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Seed,
		&i.IDField,
		&i.IDStrategy,
		&i.NextSerial,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const collectionForReset = `-- name: CollectionForReset :one
select seed, id_field, id_strategy from collections where id = $1 for update
`

type CollectionForResetRow struct {
	Seed       []byte
	IDField    string
	IDStrategy string
}

// CollectionForReset reads what rebuilding the collection from its seed needs,
// and holds the row while it happens. The lock is what stops two resets — or a
// reset and a create — from interleaving their identifier allocation and
// leaving the counter pointing at an id that already exists.
func (q *Queries) CollectionForReset(ctx context.Context, id pgtype.UUID) (CollectionForResetRow, error) {
	row := q.db.QueryRow(ctx, collectionForReset, id)
	var i CollectionForResetRow
	err := row.Scan(&i.Seed, &i.IDField, &i.IDStrategy)
	return i, err
}

const collectionIDField = `-- name: CollectionIDField :one
select id_field from collections where id = $1
`

// CollectionIDField is what a write needs to know before it can put the
// identifier back into the document: which field carries it.
func (q *Queries) CollectionIDField(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, collectionIDField, id)
	var id_field string
	err := row.Scan(&id_field)
	return id_field, err
}

const collectionsByProject = `-- name: CollectionsByProject :many
select c.id, c.project_id, c.name, c.seed, c.id_field, c.id_strategy, c.next_serial, c.created_at, c.updated_at, (select count(*) from documents d where d.collection_id = c.id) as document_count
from collections c
join projects p on p.id = c.project_id
where c.project_id = $1 and p.owner_id = $2
order by c.name
`

type CollectionsByProjectParams struct {
	ProjectID pgtype.UUID
	OwnerID   pgtype.UUID
}

type CollectionsByProjectRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Name          string
	Seed          []byte
	IDField       string
	IDStrategy    string
	NextSerial    int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DocumentCount int64
}

// CollectionsByProject drives the list on the project page. The document count
// comes with it because "how much is in there" is the first thing anyone
// looking at the list wants to know.
func (q *Queries) CollectionsByProject(ctx context.Context, arg CollectionsByProjectParams) ([]CollectionsByProjectRow, error) {
	rows, err := q.db.Query(ctx, collectionsByProject, arg.ProjectID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionsByProjectRow{}
	for rows.Next() {
		var i CollectionsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Seed,
			&i.IDField,
			&i.IDStrategy,
			&i.NextSerial,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCollection = `-- name: CreateCollection :one

insert into collections (project_id, name, seed, id_field, id_strategy)
select $1, $2, $3, $4, $5
from projects p
where p.id = $1 and p.owner_id = $6
returning id, project_id, name, seed, id_field, id_strategy, next_serial, created_at, updated_at
`

type CreateCollectionParams struct {
	ProjectID  pgtype.UUID
	Name       string
	Seed       []byte
	IDField    string
	IDStrategy string
	OwnerID    pgtype.UUID
}

// Queries for collections.
//
// Scoped by owner through a join on projects, for the same reason the endpoint
// queries are: a collection in somebody else's project must be
// indistinguishable from one that never existed, and the surest way to get that
// is to put the ownership test in the SQL.
//
// The statements about *documents* are not here. They are built at run time in
// internal/core/document.go, because a listing carries an arbitrary number of
// field filters and a sort key chosen by the caller, and sqlc generates static
// statements. The two collection statements at the bottom are the exception
// within this file: they serve unauthenticated mock traffic, which has no owner
// to scope by.
func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ProjectID,
		arg.Name,
		arg.Seed,
		arg.IDField,
		arg.IDStrategy,
		arg.OwnerID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Seed,
		&i.IDField,
		&i.IDStrategy,
		&i.NextSerial,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :execrows
delete from collections c
using projects p
where c.id = $1 and p.id = c.project_id and p.owner_id = $2
`

type DeleteCollectionParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollection, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNextSerial = `-- name: SetNextSerial :exec
update collections set next_serial = $1, updated_at = now() where id = $2
`

type SetNextSerialParams struct {
	NextSerial int64
	ID         pgtype.UUID
}

func (q *Queries) SetNextSerial(ctx context.Context, arg SetNextSerialParams) error {
	_, err := q.db.Exec(ctx, setNextSerial, arg.NextSerial, arg.ID)
	return err
}

const updateCollection = `-- name: UpdateCollection :one
update collections c
set name        = $1,
    seed        = $2,
    id_field    = $3,
    id_strategy = $4,
    updated_at  = now()
from projects p
where c.id = $5 and p.id = c.project_id and p.owner_id = $6
returning c.id, c.project_id, c.name, c.seed, c.id_field, c.id_strategy, c.next_serial, c.created_at, c.updated_at
`

type UpdateCollectionParams struct {
	Name       string
	Seed       []byte
	IDField    string
	IDStrategy string
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.Name,
		arg.Seed,
		arg.IDField,
		arg.IDStrategy,
		arg.ID,
		arg.OwnerID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Seed,
		&i.IDField,
		&i.IDStrategy,
		&i.NextSerial,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
