// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package dbgen

import (
	"context"
)

// iteratorForInsertExchanges implements pgx.CopyFromSource.
type iteratorForInsertExchanges struct {
	rows                 []InsertExchangesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertExchanges) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertExchanges) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ProjectID,
		r.rows[0].EndpointID,
		r.rows[0].Direction,
		r.rows[0].Matched,
		r.rows[0].Method,
		r.rows[0].Path,
		r.rows[0].Query,
		r.rows[0].RequestHeaders,
		r.rows[0].RequestBody,
		r.rows[0].RequestBodyTruncated,
		r.rows[0].StatusCode,
		r.rows[0].ResponseHeaders,
		r.rows[0].ResponseBody,
		r.rows[0].ResponseBodyTruncated,
		r.rows[0].DurationMs,
		r.rows[0].RemoteAddr,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForInsertExchanges) Err() error {
	return nil
}

// Queries for the request log.
//
// Exchanges carry no owner column and no foreign keys: it is the write-heavy
// table, and rows leave it by dropping a partition rather than by cascade. The
// ownership check therefore happens one step earlier — a handler resolves the
// project through ProjectByOwnerAndSlug and only then asks for its exchanges,
// so a project id reaching these statements has already been proved to belong
// to the caller.
//
// The partition statements are not here. Their table names contain the month
// they cover, so they are assembled in internal/core/partition.go with quoted
// identifiers; sqlc generates static SQL and cannot name a table that does not
// exist yet.
// InsertExchanges is the batching writer's statement. COPY rather than INSERT
// because this is the one path in the application that writes in bulk, and it
// writes on every mock request; the whole point of the queue behind it is that
// the cost per request stays off the request path.
//
// created_at is supplied rather than defaulted: it is the partition key, and
// the value that belongs to a row is when the request finished, not when the
// batch holding it happened to reach the database.
func (q *Queries) InsertExchanges(ctx context.Context, arg []InsertExchangesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"exchanges"}, []string{"id", "project_id", "endpoint_id", "direction", "matched", "method", "path", "query", "request_headers", "request_body", "request_body_truncated", "status_code", "response_headers", "response_body", "response_body_truncated", "duration_ms", "remote_addr", "created_at"}, &iteratorForInsertExchanges{rows: arg})
}
