// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCollectionEndpoint = `-- name: CreateCollectionEndpoint :one
insert into endpoints (
    project_id, method, path_pattern, kind, is_enabled, delay_ms,
    collection_id, response_headers
)
select $1, $2, $3, 'collection', $4, $5,
       $6, $7
from projects p
join collections c on c.project_id = p.id
where p.id = $1 and p.owner_id = $8 and c.id = $6
returning id, project_id, method, path_pattern, kind, is_enabled, delay_ms, status_code, response_body, collection_id, response_headers, created_at, updated_at
`

type CreateCollectionEndpointParams struct {
	ProjectID       pgtype.UUID
	Method          string
	PathPattern     string
	IsEnabled       bool
	DelayMs         int32
	CollectionID    pgtype.UUID
	ResponseHeaders []byte
	OwnerID         pgtype.UUID
}

// CreateCollectionEndpoint joins collections as well as projects, so that a
// collection id belonging to another project cannot be attached to this one.
func (q *Queries) CreateCollectionEndpoint(ctx context.Context, arg CreateCollectionEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createCollectionEndpoint,
		arg.ProjectID,
		arg.Method,
		arg.PathPattern,
		arg.IsEnabled,
		arg.DelayMs,
		arg.CollectionID,
		arg.ResponseHeaders,
		arg.OwnerID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Method,
		&i.PathPattern,
		&i.Kind,
		&i.IsEnabled,
		&i.DelayMs,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CollectionID,
		&i.ResponseHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEndpoint = `-- name: CreateEndpoint :one


insert into endpoints (
    project_id, method, path_pattern, kind, is_enabled, delay_ms,
    status_code, response_body, response_headers
)
select $1, $2, $3, 'static', $4, $5,
       $6, $7, $8
from projects p
where p.id = $1 and p.owner_id = $9
returning id, project_id, method, path_pattern, kind, is_enabled, delay_ms, status_code, response_body, collection_id, response_headers, created_at, updated_at
`

type CreateEndpointParams struct {
	ProjectID       pgtype.UUID
	Method          string
	PathPattern     string
	IsEnabled       bool
	DelayMs         int32
	StatusCode      pgtype.Int2
	ResponseBody    pgtype.Text
	ResponseHeaders []byte
	OwnerID         pgtype.UUID
}

// Queries for endpoints.
//
// The management statements are scoped by owner through a join on projects, for
// the same reason the project queries are scoped by owner_id: an endpoint in
// somebody else's project must be indistinguishable from one that never existed,
// and the surest way to get that is to put the ownership test in the SQL.
//
// The two statements at the bottom are the exception. They feed the in-memory
// route table, which serves unauthenticated mock traffic and therefore reads
// across every account by design.
// The two kinds get a statement each rather than one statement with nullable
// parameters. `endpoints_kind_fields` requires a status code and no collection
// for 'static' and the reverse for 'collection', so a single statement would be
// one the constraint can refuse depending on what was passed — and the failure
// would arrive as a check violation rather than as a message beside a field.
// Two statements each satisfy the constraint by construction.
func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.ProjectID,
		arg.Method,
		arg.PathPattern,
		arg.IsEnabled,
		arg.DelayMs,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ResponseHeaders,
		arg.OwnerID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Method,
		&i.PathPattern,
		&i.Kind,
		&i.IsEnabled,
		&i.DelayMs,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CollectionID,
		&i.ResponseHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :execrows
delete from endpoints e
using projects p
where e.id = $1 and p.id = e.project_id and p.owner_id = $2
`

type DeleteEndpointParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndpoint, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endpointByOwnerAndID = `-- name: EndpointByOwnerAndID :one
select e.id, e.project_id, e.method, e.path_pattern, e.kind, e.is_enabled, e.delay_ms, e.status_code, e.response_body, e.collection_id, e.response_headers, e.created_at, e.updated_at from endpoints e
join projects p on p.id = e.project_id
where e.id = $1 and p.owner_id = $2
`

type EndpointByOwnerAndIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) EndpointByOwnerAndID(ctx context.Context, arg EndpointByOwnerAndIDParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, endpointByOwnerAndID, arg.ID, arg.OwnerID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Method,
		&i.PathPattern,
		&i.Kind,
		&i.IsEnabled,
		&i.DelayMs,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CollectionID,
		&i.ResponseHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endpointsByProject = `-- name: EndpointsByProject :many
select e.id, e.project_id, e.method, e.path_pattern, e.kind, e.is_enabled, e.delay_ms, e.status_code, e.response_body, e.collection_id, e.response_headers, e.created_at, e.updated_at from endpoints e
join projects p on p.id = e.project_id
where e.project_id = $1 and p.owner_id = $2
order by e.path_pattern, e.method
`

type EndpointsByProjectParams struct {
	ProjectID pgtype.UUID
	OwnerID   pgtype.UUID
}

// EndpointsByProject drives the list on the project page. Ordered by path so
// that routes sharing a prefix sit together, which is how they are read.
func (q *Queries) EndpointsByProject(ctx context.Context, arg EndpointsByProjectParams) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, endpointsByProject, arg.ProjectID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Method,
			&i.PathPattern,
			&i.Kind,
			&i.IsEnabled,
			&i.DelayMs,
			&i.StatusCode,
			&i.ResponseBody,
			&i.CollectionID,
			&i.ResponseHeaders,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mockEndpoints = `-- name: MockEndpoints :many
select e.id, e.project_id, e.method, e.path_pattern, e.kind, e.is_enabled, e.delay_ms, e.status_code, e.response_body, e.collection_id, e.response_headers, e.created_at, e.updated_at, p.slug as project_slug from endpoints e
join projects p on p.id = e.project_id
where e.is_enabled
order by e.path_pattern, e.method
`

type MockEndpointsRow struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	Method          string
	PathPattern     string
	Kind            string
	IsEnabled       bool
	DelayMs         int32
	StatusCode      pgtype.Int2
	ResponseBody    pgtype.Text
	CollectionID    pgtype.UUID
	ResponseHeaders []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ProjectSlug     string
}

// MockEndpoints is everything the route table serves. Disabled endpoints are
// left out rather than filtered at match time, so a disabled route is invisible
// to the matcher instead of being a case it has to remember.
func (q *Queries) MockEndpoints(ctx context.Context) ([]MockEndpointsRow, error) {
	rows, err := q.db.Query(ctx, mockEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MockEndpointsRow{}
	for rows.Next() {
		var i MockEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Method,
			&i.PathPattern,
			&i.Kind,
			&i.IsEnabled,
			&i.DelayMs,
			&i.StatusCode,
			&i.ResponseBody,
			&i.CollectionID,
			&i.ResponseHeaders,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mockProjects = `-- name: MockProjects :many
select id, slug from projects
`

type MockProjectsRow struct {
	ID   pgtype.UUID
	Slug string
}

// MockProjects lists every project, including those with no endpoints yet. The
// route table needs them: "this project has nothing defined" and "there is no
// such project" are different answers, and only the endpoint rows would not
// tell them apart.
func (q *Queries) MockProjects(ctx context.Context) ([]MockProjectsRow, error) {
	rows, err := q.db.Query(ctx, mockProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MockProjectsRow{}
	for rows.Next() {
		var i MockProjectsRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollectionEndpoint = `-- name: UpdateCollectionEndpoint :one
update endpoints e
set method           = $1,
    path_pattern     = $2,
    kind             = 'collection',
    is_enabled       = $3,
    delay_ms         = $4,
    status_code      = null,
    response_body    = null,
    collection_id    = $5,
    response_headers = $6,
    updated_at       = now()
from projects p, collections c
where e.id = $7 and p.id = e.project_id and p.owner_id = $8
  and c.id = $5 and c.project_id = p.id
returning e.id, e.project_id, e.method, e.path_pattern, e.kind, e.is_enabled, e.delay_ms, e.status_code, e.response_body, e.collection_id, e.response_headers, e.created_at, e.updated_at
`

type UpdateCollectionEndpointParams struct {
	Method          string
	PathPattern     string
	IsEnabled       bool
	DelayMs         int32
	CollectionID    pgtype.UUID
	ResponseHeaders []byte
	ID              pgtype.UUID
	OwnerID         pgtype.UUID
}

func (q *Queries) UpdateCollectionEndpoint(ctx context.Context, arg UpdateCollectionEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateCollectionEndpoint,
		arg.Method,
		arg.PathPattern,
		arg.IsEnabled,
		arg.DelayMs,
		arg.CollectionID,
		arg.ResponseHeaders,
		arg.ID,
		arg.OwnerID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Method,
		&i.PathPattern,
		&i.Kind,
		&i.IsEnabled,
		&i.DelayMs,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CollectionID,
		&i.ResponseHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEndpoint = `-- name: UpdateEndpoint :one
update endpoints e
set method           = $1,
    path_pattern     = $2,
    kind             = 'static',
    is_enabled       = $3,
    delay_ms         = $4,
    status_code      = $5,
    response_body    = $6,
    collection_id    = null,
    response_headers = $7,
    updated_at       = now()
from projects p
where e.id = $8 and p.id = e.project_id and p.owner_id = $9
returning e.id, e.project_id, e.method, e.path_pattern, e.kind, e.is_enabled, e.delay_ms, e.status_code, e.response_body, e.collection_id, e.response_headers, e.created_at, e.updated_at
`

type UpdateEndpointParams struct {
	Method          string
	PathPattern     string
	IsEnabled       bool
	DelayMs         int32
	StatusCode      pgtype.Int2
	ResponseBody    pgtype.Text
	ResponseHeaders []byte
	ID              pgtype.UUID
	OwnerID         pgtype.UUID
}

// Both update statements write `kind` and both sides of the kind-specific
// columns, so that changing an endpoint from one kind to the other leaves no
// remnant of what it was. Setting only the columns the new kind uses would
// leave the old ones populated and the check constraint would refuse the row.
func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.Method,
		arg.PathPattern,
		arg.IsEnabled,
		arg.DelayMs,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ResponseHeaders,
		arg.ID,
		arg.OwnerID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Method,
		&i.PathPattern,
		&i.Kind,
		&i.IsEnabled,
		&i.DelayMs,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CollectionID,
		&i.ResponseHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
