// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchanges.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const exchangeByID = `-- name: ExchangeByID :one
select id, project_id, endpoint_id, direction, matched, method, path, query, request_headers, request_body, request_body_truncated, status_code, response_headers, response_body, response_body_truncated, duration_ms, remote_addr, created_at from exchanges
where project_id = $1 and id = $2
`

type ExchangeByIDParams struct {
	ProjectID pgtype.UUID
	ID        pgtype.UUID
}

// ExchangeByID is the detail view. The project is part of the lookup so that an
// exchange id from another account's project is the same 404 as one that never
// existed — the table itself has no owner to scope by.
func (q *Queries) ExchangeByID(ctx context.Context, arg ExchangeByIDParams) (Exchange, error) {
	row := q.db.QueryRow(ctx, exchangeByID, arg.ProjectID, arg.ID)
	var i Exchange
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EndpointID,
		&i.Direction,
		&i.Matched,
		&i.Method,
		&i.Path,
		&i.Query,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.RequestBodyTruncated,
		&i.StatusCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ResponseBodyTruncated,
		&i.DurationMs,
		&i.RemoteAddr,
		&i.CreatedAt,
	)
	return i, err
}

const exchangesByProject = `-- name: ExchangesByProject :many
select id, project_id, endpoint_id, direction, matched, method, path, query, request_headers, request_body, request_body_truncated, status_code, response_headers, response_body, response_body_truncated, duration_ms, remote_addr, created_at from exchanges
where project_id = $1
  and ($2::timestamptz is null
       or (created_at, id) < ($2::timestamptz, $3::uuid))
order by created_at desc, id desc
limit $4
`

type ExchangesByProjectParams struct {
	ProjectID pgtype.UUID
	BeforeAt  pgtype.Timestamptz
	BeforeID  pgtype.UUID
	PageLimit int32
}

// ExchangesByProject is the inspector's list: newest first, one page at a time.
//
// The cursor is the (created_at, id) pair of the last row on the page before,
// compared as a row rather than as two columns, so that several exchanges
// sharing a timestamp still page through exactly once. A null cursor means the
// first page, which is why the whole comparison is guarded rather than the
// caller having to invent a timestamp far enough in the future.
func (q *Queries) ExchangesByProject(ctx context.Context, arg ExchangesByProjectParams) ([]Exchange, error) {
	rows, err := q.db.Query(ctx, exchangesByProject,
		arg.ProjectID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exchange{}
	for rows.Next() {
		var i Exchange
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EndpointID,
			&i.Direction,
			&i.Matched,
			&i.Method,
			&i.Path,
			&i.Query,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.RequestBodyTruncated,
			&i.StatusCode,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.ResponseBodyTruncated,
			&i.DurationMs,
			&i.RemoteAddr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exchangesSince = `-- name: ExchangesSince :many
select id, project_id, endpoint_id, direction, matched, method, path, query, request_headers, request_body, request_body_truncated, status_code, response_headers, response_body, response_body_truncated, duration_ms, remote_addr, created_at from exchanges
where project_id = $1
  and (created_at, id) > ($2::timestamptz, $3::uuid)
order by created_at, id
limit $4
`

type ExchangesSinceParams struct {
	ProjectID pgtype.UUID
	AfterAt   pgtype.Timestamptz
	AfterID   pgtype.UUID
	PageLimit int32
}

// ExchangesSince is the live tail: everything recorded after the cursor, oldest
// first, so that a stream appends them in the order they happened.
func (q *Queries) ExchangesSince(ctx context.Context, arg ExchangesSinceParams) ([]Exchange, error) {
	rows, err := q.db.Query(ctx, exchangesSince,
		arg.ProjectID,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exchange{}
	for rows.Next() {
		var i Exchange
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EndpointID,
			&i.Direction,
			&i.Matched,
			&i.Method,
			&i.Path,
			&i.Query,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.RequestBodyTruncated,
			&i.StatusCode,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.ResponseBodyTruncated,
			&i.DurationMs,
			&i.RemoteAddr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertExchangesParams struct {
	ID                    pgtype.UUID
	ProjectID             pgtype.UUID
	EndpointID            pgtype.UUID
	Direction             string
	Matched               bool
	Method                string
	Path                  string
	Query                 pgtype.Text
	RequestHeaders        []byte
	RequestBody           []byte
	RequestBodyTruncated  bool
	StatusCode            pgtype.Int2
	ResponseHeaders       []byte
	ResponseBody          []byte
	ResponseBodyTruncated bool
	DurationMs            int32
	RemoteAddr            *netip.Addr
	CreatedAt             pgtype.Timestamptz
}

const latestExchangeCursor = `-- name: LatestExchangeCursor :one
select created_at, id from exchanges
where project_id = $1
order by created_at desc, id desc
limit 1
`

type LatestExchangeCursorRow struct {
	CreatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// LatestExchangeCursor is where a live tail starts: the newest row already on
// the page, so the stream sends what arrives after it and not the page again.
func (q *Queries) LatestExchangeCursor(ctx context.Context, projectID pgtype.UUID) (LatestExchangeCursorRow, error) {
	row := q.db.QueryRow(ctx, latestExchangeCursor, projectID)
	var i LatestExchangeCursorRow
	err := row.Scan(&i.CreatedAt, &i.ID)
	return i, err
}
