// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package dbgen

import (
	"context"
)

const checkDatabase = `-- name: CheckDatabase :one

select 1 as ok
`

// Queries backing the readiness probe.
// CheckDatabase is what /readyz asks. It is trivial on purpose: the point is
// not the answer but that the pool handed out a connection and the server
// planned and ran a statement on it.
func (q *Queries) CheckDatabase(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkDatabase)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
