// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	Prefix     string
	TokenHash  []byte
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Collection struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Seed       []byte
	IDField    string
	IDStrategy string
	NextSerial int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Document struct {
	ID           pgtype.UUID
	CollectionID pgtype.UUID
	PublicID     string
	Body         []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Seq          int64
}

type Endpoint struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	Method          string
	PathPattern     string
	Kind            string
	IsEnabled       bool
	DelayMs         int32
	StatusCode      pgtype.Int2
	ResponseBody    pgtype.Text
	CollectionID    pgtype.UUID
	ResponseHeaders []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Exchange struct {
	ID                    pgtype.UUID
	ProjectID             pgtype.UUID
	EndpointID            pgtype.UUID
	Direction             string
	Matched               bool
	Method                string
	Path                  string
	Query                 pgtype.Text
	RequestHeaders        []byte
	RequestBody           []byte
	RequestBodyTruncated  bool
	StatusCode            pgtype.Int2
	ResponseHeaders       []byte
	ResponseBody          []byte
	ResponseBodyTruncated bool
	DurationMs            int32
	RemoteAddr            *netip.Addr
	CreatedAt             pgtype.Timestamptz
}

type ExchangesDefault struct {
	ID                    pgtype.UUID
	ProjectID             pgtype.UUID
	EndpointID            pgtype.UUID
	Direction             string
	Matched               bool
	Method                string
	Path                  string
	Query                 pgtype.Text
	RequestHeaders        []byte
	RequestBody           []byte
	RequestBodyTruncated  bool
	StatusCode            pgtype.Int2
	ResponseHeaders       []byte
	ResponseBody          []byte
	ResponseBodyTruncated bool
	DurationMs            int32
	RemoteAddr            *netip.Addr
	CreatedAt             pgtype.Timestamptz
}

type Project struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Slug      string
	Name      string
	IsDemo    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
