// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one

insert into projects (owner_id, slug, name, is_demo)
values ($1, $2, $3, $4)
returning id, owner_id, slug, name, is_demo, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID pgtype.UUID
	Slug    string
	Name    string
	IsDemo  bool
}

// Queries for projects.
//
// Every statement is scoped by owner_id as well as by the row's own key. A
// project that belongs to somebody else must be indistinguishable from one that
// does not exist, and the surest way to get that is to make the ownership test
// part of the query rather than a check the caller might forget.
// CreateProject takes is_demo because the shared demo project is created by the
// application at startup and is otherwise an ordinary project. No form can set
// it: the flag arrives from core.EnsureDemoProject and nowhere else.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Slug,
		arg.Name,
		arg.IsDemo,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
delete from projects where id = $1 and owner_id = $2
`

type DeleteProjectParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// DeleteProject reports the number of rows removed, which is how the caller
// tells "deleted" from "never yours in the first place". Endpoints, collections
// and documents go with it through on delete cascade.
func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const projectByOwnerAndSlug = `-- name: ProjectByOwnerAndSlug :one
select id, owner_id, slug, name, is_demo, created_at, updated_at from projects
where owner_id = $1 and slug = $2
`

type ProjectByOwnerAndSlugParams struct {
	OwnerID pgtype.UUID
	Slug    string
}

func (q *Queries) ProjectByOwnerAndSlug(ctx context.Context, arg ProjectByOwnerAndSlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, projectByOwnerAndSlug, arg.OwnerID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectBySlug = `-- name: ProjectBySlug :one
select id, owner_id, slug, name, is_demo, created_at, updated_at from projects where slug = $1
`

// ProjectBySlug is the one project lookup with no owner in it. The demo project
// has an owner nobody can log in as, so provisioning it at startup has no user
// to scope by; the slug it uses is reserved, so no account's project can hold
// it.
func (q *Queries) ProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, projectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectsByOwner = `-- name: ProjectsByOwner :many
select id, owner_id, slug, name, is_demo, created_at, updated_at from projects
where owner_id = $1
order by created_at desc, slug
`

// ProjectsByOwner drives the project list. Newest first: the one just created
// is the one being looked for.
func (q *Queries) ProjectsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, projectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Name,
			&i.IsDemo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
update projects
set slug = $1, name = $2, updated_at = now()
where id = $3 and owner_id = $4
returning id, owner_id, slug, name, is_demo, created_at, updated_at
`

type UpdateProjectParams struct {
	Slug    string
	Name    string
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// UpdateProject changes the two fields a user may edit. Renaming the slug
// changes the project's mock URL, which is the user's decision to make.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Slug,
		arg.Name,
		arg.ID,
		arg.OwnerID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
