// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aPITokensByUser = `-- name: APITokensByUser :many
select id, user_id, name, prefix, token_hash, last_used_at, expires_at, created_at from api_tokens
where user_id = $1
order by created_at desc
`

// APITokensByUser drives the tokens page. Newest first: the one just created is
// the one being looked for.
func (q *Queries) APITokensByUser(ctx context.Context, userID pgtype.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, aPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.TokenHash,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authenticateAPIToken = `-- name: AuthenticateAPIToken :one
with touched as (
    update api_tokens
    set last_used_at = now()
    where token_hash = $1
      and (expires_at is null or expires_at > now())
    returning id, user_id, name, prefix, token_hash, last_used_at, expires_at, created_at
)
select
    t.id, t.user_id, t.name, t.prefix, t.last_used_at, t.expires_at, t.created_at,
    u.email      as user_email,
    u.created_at as user_created_at,
    u.updated_at as user_updated_at
from touched t
join users u on u.id = t.user_id
`

type AuthenticateAPITokenRow struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Name          string
	Prefix        string
	LastUsedAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UserEmail     string
	UserCreatedAt pgtype.Timestamptz
	UserUpdatedAt pgtype.Timestamptz
}

// AuthenticateAPIToken resolves a presented token to its owner and marks it
// used, in one statement.
//
// The update and the lookup are one statement because they are one question:
// "is this token good, and whose is it". Two statements would leave a window in
// which a token revoked between them still answered. An expired token matches
// nothing, so expiry needs no second check in Go — and the same row therefore
// does not get its last_used_at bumped by a request it did not authorise.
//
// The lookup is by hash, on the unique index, so it costs one index probe. No
// constant-time comparison is needed or possible here: what is compared is a
// SHA-256 of 32 random bytes, and the database is matching it as an index key.
func (q *Queries) AuthenticateAPIToken(ctx context.Context, tokenHash []byte) (AuthenticateAPITokenRow, error) {
	row := q.db.QueryRow(ctx, authenticateAPIToken, tokenHash)
	var i AuthenticateAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserEmail,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const createAPIToken = `-- name: CreateAPIToken :one

insert into api_tokens (user_id, name, prefix, token_hash, expires_at)
values ($1, $2, $3, $4, $5)
returning id, user_id, name, prefix, token_hash, last_used_at, expires_at, created_at
`

type CreateAPITokenParams struct {
	UserID    pgtype.UUID
	Name      string
	Prefix    string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

// Queries for API tokens.
//
// A token row never holds the token. It holds the SHA-256 of it, a short
// non-secret prefix so the owner can tell one row from another after the
// plaintext is gone, and the name they gave it. Everything that reads a token
// back out reads those three; nothing in the schema can reconstruct the secret.
//
// The listing statements are scoped by user_id for the same reason the project
// statements are scoped by owner_id: somebody else's token must be
// indistinguishable from one that never existed.
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
delete from api_tokens where id = $1 and user_id = $2
`

type DeleteAPITokenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// DeleteAPIToken reports the number of rows removed, which is how the caller
// tells "revoked" from "never yours in the first place".
func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
