// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

insert into users (email, password_hash)
values ($1, $2)
returning id, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

// Queries for accounts.
// CreateUser fails with a unique violation on a duplicate address. The check is
// left to the constraint rather than done as a prior SELECT, because between
// that SELECT and this INSERT another registration can slip in.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :execrows
update users
set password_hash = $1, updated_at = now()
where id = $2
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           pgtype.UUID
}

// UpdatePassword also bumps updated_at, which is the record of when the
// credential last changed.
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userByEmail = `-- name: UserByEmail :one
select id, email, password_hash, created_at, updated_at from users where email = $1
`

// UserByEmail is the login lookup. `email` is citext, so the comparison is
// case-insensitive in the database rather than in Go.
func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
select id, email, password_hash, created_at, updated_at from users where id = $1
`

// UserByID resolves the id held in the session cookie on every request that
// needs to know who is asking.
func (q *Queries) UserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
