package core

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"net/url"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// Document is one JSON object in a collection.
type Document struct {
	// PublicID is the identifier as clients see it in URLs. It is kept apart
	// from the row's primary key so that seeded data keeps the ids its fixture
	// gave it.
	PublicID  string
	Body      json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

// DocumentPage is one page of a listing together with how many documents the
// filters matched in total, which is what the X-Total-Count header reports and
// what a client needs to know how many pages there are.
type DocumentPage struct {
	Documents []Document
	Total     int
}

// Listing limits. The default is a page rather than everything, because a
// listing with no limit is a promise that gets harder to keep as somebody's
// fixture grows, and X-Total-Count says what was left out.
const (
	DefaultListLimit = 100
	MaxListLimit     = 1000
)

// Reserved listing parameters. Everything else in a query string is a field
// filter, which is why these all start with an underscore: a collection with a
// field called `page` should still be filterable on it.
const (
	paramPage  = "_page"
	paramLimit = "_limit"
	paramSort  = "_sort"
	paramOrder = "_order"
)

var listParams = []string{paramPage, paramLimit, paramSort, paramOrder}

// QueryError is a listing query the server will not guess at — a `_limit` that
// is not a number, a `_order` that is neither direction. It is a distinct type
// because the answer to it is 400 with the message shown to the client, and not
// the 500 that any other error from this package earns.
type QueryError struct{ Message string }

func (e QueryError) Error() string { return e.Message }

func queryErrorf(format string, args ...any) error {
	return QueryError{Message: fmt.Sprintf(format, args...)}
}

// ErrNotObject reports a request body that is not a JSON object. Every document
// in a collection is an object: an array or a bare number has no fields to
// filter, merge or address.
var ErrNotObject = errors.New("document must be a JSON object")

// ListQuery is a decoded listing request.
type ListQuery struct {
	// Page counts from one.
	Page  int
	Limit int
	// Sort is the document field to order by, or "" for insertion order.
	Sort string
	Desc bool
	// Filters are ANDed together; the values within one filter are ORed, so
	// ?status=active&status=trial asks for either.
	Filters []Filter
}

// Filter is one field=value constraint from the query string.
type Filter struct {
	Field  string
	Values []string
}

// ParseListQuery reads the listing parameters and the field filters out of a
// query string.
//
// An unknown underscore-prefixed parameter is refused rather than ignored. The
// underscore namespace is the server's, so `?_limits=5` is a typo and not a
// filter on a field called `_limits`; silently returning the first hundred
// documents would look like the parameter had worked.
func ParseListQuery(values url.Values) (ListQuery, error) {
	q := ListQuery{Page: 1, Limit: DefaultListLimit}

	if raw := values.Get(paramPage); raw != "" {
		page, err := strconv.Atoi(raw)
		if err != nil || page < 1 {
			return ListQuery{}, queryErrorf("_page must be a whole number from 1 upwards, not %q", raw)
		}
		q.Page = page
	}
	if raw := values.Get(paramLimit); raw != "" {
		limit, err := strconv.Atoi(raw)
		if err != nil || limit < 1 || limit > MaxListLimit {
			return ListQuery{}, queryErrorf("_limit must be a whole number between 1 and %d, not %q", MaxListLimit, raw)
		}
		q.Limit = limit
	}
	if raw := strings.TrimSpace(values.Get(paramSort)); raw != "" {
		q.Sort = raw
	}
	switch order := strings.ToLower(strings.TrimSpace(values.Get(paramOrder))); order {
	case "", "asc":
	case "desc":
		q.Desc = true
	default:
		return ListQuery{}, queryErrorf("_order must be asc or desc, not %q", order)
	}

	// Sorted, so that the SQL a given query string builds is the same string
	// every time and Postgres can reuse its plan.
	for _, field := range slices.Sorted(maps.Keys(values)) {
		if strings.HasPrefix(field, "_") {
			if !slices.Contains(listParams, field) {
				return ListQuery{}, queryErrorf("%s is not a listing parameter. The ones there are: %s",
					field, strings.Join(listParams, ", "))
			}
			continue
		}
		q.Filters = append(q.Filters, Filter{Field: field, Values: values[field]})
	}
	return q, nil
}

// ListDocuments answers a listing.
//
// The statement is assembled here rather than generated by sqlc because the
// number of filters and the sort key come from the request. Every value still
// travels as a bind parameter — including the sort key, which is applied as
// `body -> $n` rather than pasted into the ORDER BY — so nothing a client sends
// reaches the parser as SQL.
func (s *Store) ListDocuments(ctx context.Context, collectionID uuid.UUID, q ListQuery) (DocumentPage, error) {
	args := []any{fromUUID(collectionID)}
	where := documentFilterSQL(q.Filters, &args)

	order := "order by seq" + direction(q.Desc)
	if q.Sort != "" {
		args = append(args, q.Sort)
		// nulls last in both directions, so a document missing the sort field
		// sits at the end rather than at whichever end the direction put it.
		// seq breaks the ties, which is what makes paging through equal values
		// return each document once.
		order = fmt.Sprintf("order by body -> $%d%s nulls last, seq", len(args), direction(q.Desc))
	}

	args = append(args, q.Limit)
	limit := len(args)
	args = append(args, (q.Page-1)*q.Limit)
	offset := len(args)

	// count(*) over () is evaluated before LIMIT, so one statement answers both
	// "which documents" and "how many in total".
	list := fmt.Sprintf(`
		select public_id, body, created_at, updated_at, count(*) over () as total
		from documents %s %s limit $%d offset $%d`, where, order, limit, offset)

	rows, err := s.pool.Query(ctx, list, args...)
	if err != nil {
		return DocumentPage{}, fmt.Errorf("list documents: %w", err)
	}
	defer rows.Close()

	page := DocumentPage{Documents: []Document{}}
	for rows.Next() {
		var doc Document
		var body []byte
		var createdAt, updatedAt time.Time
		var total int64
		if err := rows.Scan(&doc.PublicID, &body, &createdAt, &updatedAt, &total); err != nil {
			return DocumentPage{}, fmt.Errorf("scan document: %w", err)
		}
		doc.Body = json.RawMessage(body)
		doc.CreatedAt, doc.UpdatedAt = createdAt, updatedAt
		page.Documents = append(page.Documents, doc)
		page.Total = int(total)
	}
	if err := rows.Err(); err != nil {
		return DocumentPage{}, fmt.Errorf("list documents: %w", err)
	}

	// A page past the end returns no rows, and with them no window function to
	// read the total from. Asking separately is worth one extra statement in the
	// one case it happens: a client paging through wants to be told it has run
	// off the end, not that the collection is empty.
	if len(page.Documents) == 0 {
		total, err := s.countDocuments(ctx, collectionID, q.Filters)
		if err != nil {
			return DocumentPage{}, err
		}
		page.Total = total
	}
	return page, nil
}

func (s *Store) countDocuments(ctx context.Context, collectionID uuid.UUID, filters []Filter) (int, error) {
	args := []any{fromUUID(collectionID)}
	where := documentFilterSQL(filters, &args)

	var total int
	if err := s.pool.QueryRow(ctx, "select count(*) from documents "+where, args...).Scan(&total); err != nil {
		return 0, fmt.Errorf("count documents: %w", err)
	}
	return total, nil
}

// documentFilterSQL renders the WHERE clause of a listing, appending the values
// it needs to args.
//
// Filters are containment tests — `body @> '{"status":"active"}'` — which is
// what the jsonb_path_ops GIN index on the column can answer. The alternative,
// comparing `body ->> 'status'`, would be a sequential scan of every document
// in the collection.
func documentFilterSQL(filters []Filter, args *[]any) string {
	where := "where collection_id = $1"

	for _, filter := range filters {
		var alternatives []string
		for _, value := range filter.Values {
			for _, doc := range containmentDocs(filter.Field, value) {
				*args = append(*args, doc)
				alternatives = append(alternatives, fmt.Sprintf("body @> $%d::jsonb", len(*args)))
			}
		}
		if len(alternatives) == 0 {
			continue
		}
		where += " and (" + strings.Join(alternatives, " or ") + ")"
	}
	return where
}

// containmentDocs turns one field=value pair into the jsonb documents that
// satisfy it.
//
// A query string has no types: `?id=1` could mean the number 1 or the string
// "1", and which one is right depends on a document the caller has not seen.
// Rather than guess, a value that reads as a JSON scalar is matched both ways —
// two containment tests ORed together, both of which the index can answer. So
// ?id=1 finds {"id":1} and {"id":"1"} alike, and ?name=1 still finds a document
// whose name is the string "1".
func containmentDocs(field, value string) []string {
	asString, err := json.Marshal(map[string]string{field: value})
	if err != nil {
		return nil
	}
	docs := []string{string(asString)}

	if typed, ok := jsonScalar(value); ok {
		object, err := json.Marshal(map[string]json.RawMessage{field: json.RawMessage(typed)})
		if err == nil {
			docs = append(docs, string(object))
		}
	}
	return docs
}

// jsonScalar reports whether a query-string value also reads as a JSON number,
// boolean or null, and returns it in that form.
func jsonScalar(value string) (string, bool) {
	switch value {
	case "true", "false", "null":
		return value, true
	}
	if _, err := strconv.ParseFloat(value, 64); err == nil && json.Valid([]byte(value)) {
		return value, true
	}
	return "", false
}

func direction(desc bool) string {
	if desc {
		return " desc"
	}
	return " asc"
}

// GetDocument returns one document by the identifier in its URL.
func (s *Store) GetDocument(ctx context.Context, collectionID uuid.UUID, publicID string) (Document, error) {
	const get = `
		select public_id, body, created_at, updated_at
		from documents where collection_id = $1 and public_id = $2`

	doc, err := scanDocument(s.pool.QueryRow(ctx, get, fromUUID(collectionID), publicID))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Document{}, ErrNotFound
		}
		return Document{}, fmt.Errorf("find document: %w", err)
	}
	return doc, nil
}

// createAttempts bounds the retry when an allocated identifier is already
// taken. That happens when a seed named ids the counter has not reached — reset
// moves the counter past them, but a seed edited after a reset can still leave
// one behind. Each attempt steps the counter on, so a handful is plenty.
const createAttempts = 8

// CreateDocument stores a new document and returns it as it was stored, with
// the server-assigned identifier in place.
//
// The identifier is the server's to choose. A client that sends one of its own
// has it overwritten, because two clients POSTing the same fixture would
// otherwise collide and the second would get an error from a mock server that
// exists to be predictable.
func (s *Store) CreateDocument(ctx context.Context, collectionID uuid.UUID, body []byte) (Document, error) {
	if err := checkObject(body); err != nil {
		return Document{}, err
	}

	const insert = `
		insert into documents (collection_id, public_id, body)
		values ($1, $2, $3::jsonb || jsonb_build_object($4::text, $5::jsonb))
		returning public_id, body, created_at, updated_at`

	var lastErr error
	for range createAttempts {
		allocated, err := s.q.AllocateDocumentID(ctx, fromUUID(collectionID))
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return Document{}, ErrNotFound
			}
			return Document{}, fmt.Errorf("allocate document id: %w", err)
		}

		publicID := strconv.FormatInt(allocated.Allocated, 10)
		if allocated.IDStrategy == IDUUID {
			publicID = uuid.NewString()
		}

		doc, err := scanDocument(s.pool.QueryRow(ctx, insert,
			fromUUID(collectionID), publicID, body, allocated.IDField, idJSON(publicID)))
		switch {
		case err == nil:
			return doc, nil
		case uniqueViolation(err, documentsPublicIDConstraint):
			// A seeded document already answers to this id. The counter has
			// moved on, so the next attempt asks for a different one.
			lastErr = err
			continue
		default:
			return Document{}, fmt.Errorf("create document: %w", err)
		}
	}
	return Document{}, fmt.Errorf("create document: no free identifier after %d attempts: %w", createAttempts, lastErr)
}

// documentsPublicIDConstraint is the unique index behind (collection, id).
const documentsPublicIDConstraint = "documents_collection_id_public_id_key"

// ReplaceDocument overwrites a document, keeping only its identifier. That is
// what PUT means, and the identifier is excluded because it is the thing the
// request addressed: a PUT that could rename the resource it was sent to would
// be a move, not a replace.
func (s *Store) ReplaceDocument(ctx context.Context, collectionID uuid.UUID, publicID string, body []byte) (Document, error) {
	const replace = `
		update documents
		set body       = $3::jsonb || jsonb_build_object($4::text, $5::jsonb),
		    updated_at = now()
		where collection_id = $1 and public_id = $2
		returning public_id, body, created_at, updated_at`

	return s.writeDocument(ctx, replace, collectionID, publicID, body)
}

// PatchDocument merges the request into the stored document, one level deep.
//
// Shallow is the whole point and jsonb's `||` is exactly it: a nested object in
// the request replaces the nested object in the document rather than being
// merged into it. A deep merge would leave no way to remove a nested field,
// and PUT is there for callers who want to say what the whole document is.
func (s *Store) PatchDocument(ctx context.Context, collectionID uuid.UUID, publicID string, body []byte) (Document, error) {
	const patch = `
		update documents
		set body       = body || $3::jsonb || jsonb_build_object($4::text, $5::jsonb),
		    updated_at = now()
		where collection_id = $1 and public_id = $2
		returning public_id, body, created_at, updated_at`

	return s.writeDocument(ctx, patch, collectionID, publicID, body)
}

// writeDocument is the shared half of PUT and PATCH: check the body, find out
// which field carries the identifier, and run the statement that puts it back.
func (s *Store) writeDocument(ctx context.Context, statement string, collectionID uuid.UUID, publicID string, body []byte) (Document, error) {
	if err := checkObject(body); err != nil {
		return Document{}, err
	}

	idField, err := s.q.CollectionIDField(ctx, fromUUID(collectionID))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Document{}, ErrNotFound
		}
		return Document{}, fmt.Errorf("read the collection id field: %w", err)
	}

	doc, err := scanDocument(s.pool.QueryRow(ctx, statement,
		fromUUID(collectionID), publicID, body, idField, idJSON(publicID)))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Document{}, ErrNotFound
		}
		return Document{}, fmt.Errorf("write document: %w", err)
	}
	return doc, nil
}

// DeleteDocument removes one document.
func (s *Store) DeleteDocument(ctx context.Context, collectionID uuid.UUID, publicID string) error {
	tag, err := s.pool.Exec(ctx,
		`delete from documents where collection_id = $1 and public_id = $2`,
		fromUUID(collectionID), publicID)
	if err != nil {
		return fmt.Errorf("delete document: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// checkObject refuses a body that is not a JSON object before it reaches the
// `documents_body_is_object` constraint, so that a client sending an array gets
// 400 and a sentence rather than 500 and a check violation in the log.
func checkObject(body []byte) error {
	trimmed := strings.TrimSpace(string(body))
	if trimmed == "" || trimmed[0] != '{' || !json.Valid(body) {
		return ErrNotObject
	}
	return nil
}

func scanDocument(row pgx.Row) (Document, error) {
	var doc Document
	var body []byte
	var createdAt, updatedAt time.Time

	if err := row.Scan(&doc.PublicID, &body, &createdAt, &updatedAt); err != nil {
		return Document{}, err
	}
	doc.Body = json.RawMessage(body)
	doc.CreatedAt, doc.UpdatedAt = createdAt, updatedAt
	return doc, nil
}
